// SPDX-License-Identifier: MIT

import Foundation

/// SF Symbol names as typed constants, so a rename is one edit.
public enum AlohaSymbol {
    public static let reply = "arrowshape.turn.up.left"
    public static let boost = "arrow.2.squarepath"
    public static let favourite = "star"
    public static let favouriteFilled = "star.fill"
    public static let bookmark = "bookmark"
    public static let bookmarkFilled = "bookmark.fill"
    public static let more = "ellipsis"
    public static let share = "square.and.arrow.up"
    public static let compose = "square.and.pencil"
    public static let refresh = "arrow.clockwise"
    public static let search = "magnifyingglass"
    public static let settings = "gearshape"
    public static let notifications = "bell"
    public static let notificationsFilled = "bell.fill"
    public static let profile = "person.crop.circle"
    public static let mute = "speaker.slash"
    public static let unmute = "speaker.wave.2"
    public static let play = "play.fill"
    public static let pause = "pause.fill"
    public static let altBadge = "text.below.photo"
    public static let sensitive = "eye.slash"
    public static let reveal = "eye"
    public static let warning = "exclamationmark.triangle"
    public static let gap = "arrow.up.arrow.down"
    public static let report = "flag"
    public static let block = "hand.raised"
    public static let translate = "character.bubble"
    public static let edit = "pencil"
    public static let delete = "trash"
    public static let pin = "pin"
    public static let list = "list.bullet"
    public static let hashtag = "number"
    public static let poll = "chart.bar"
    public static let media = "photo"
    public static let camera = "camera"
    public static let video = "video"
    public static let globe = "globe"
    public static let lock = "lock"
    public static let envelope = "envelope"
    public static let sparkles = "sparkles"
    public static let offline = "wifi.slash"
}
